In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8319, 2792, 9509, 3716],
 [8319, 2792, 9509, 9538],
 [8319, 2454, 9509, 8253],
 [894, 6282, 670, 9392, 7296],
 [894, 6282, 670, 9392, 8490],
 [737, 8319, 3952, 9509, 7799],
 [6254, 5861, 7444, 9392]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8319 2792 9509 3716]
 [   0    0    0    0 8319 2792 9509 9538]
 [   0    0    0    0 8319 2454 9509 8253]
 [   0    0    0  894 6282  670 9392 7296]
 [   0    0    0  894 6282  670 9392 8490]
 [   0    0    0  737 8319 3952 9509 7799]
 [   0    0    0    0 6254 5861 7444 9392]]


In [11]:
## feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step


array([[[-2.01622732e-02, -1.54129751e-02, -4.18285243e-02,
         -2.93314457e-03, -8.42098147e-03,  1.84124820e-02,
         -7.88030773e-03,  4.66990806e-02, -3.06868441e-02,
         -2.11154111e-02],
        [-2.01622732e-02, -1.54129751e-02, -4.18285243e-02,
         -2.93314457e-03, -8.42098147e-03,  1.84124820e-02,
         -7.88030773e-03,  4.66990806e-02, -3.06868441e-02,
         -2.11154111e-02],
        [-2.01622732e-02, -1.54129751e-02, -4.18285243e-02,
         -2.93314457e-03, -8.42098147e-03,  1.84124820e-02,
         -7.88030773e-03,  4.66990806e-02, -3.06868441e-02,
         -2.11154111e-02],
        [-2.01622732e-02, -1.54129751e-02, -4.18285243e-02,
         -2.93314457e-03, -8.42098147e-03,  1.84124820e-02,
         -7.88030773e-03,  4.66990806e-02, -3.06868441e-02,
         -2.11154111e-02],
        [ 3.04473154e-02, -1.19873285e-02, -3.95213962e-02,
         -9.00893286e-03,  3.48253585e-02,  2.31716149e-02,
          2.18813755e-02,  3.74430083e-02, -2.859542

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 8319, 2792, 9509, 3716])

In [23]:
print(embedded_docs[0].shape)
print(type(embedded_docs[0]))


(8,)
<class 'numpy.ndarray'>


In [24]:
import numpy as np
sample = np.expand_dims(embedded_docs[0], axis=0)
model.predict(sample)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[[-0.02016227, -0.01541298, -0.04182852, -0.00293314,
         -0.00842098,  0.01841248, -0.00788031,  0.04669908,
         -0.03068684, -0.02111541],
        [-0.02016227, -0.01541298, -0.04182852, -0.00293314,
         -0.00842098,  0.01841248, -0.00788031,  0.04669908,
         -0.03068684, -0.02111541],
        [-0.02016227, -0.01541298, -0.04182852, -0.00293314,
         -0.00842098,  0.01841248, -0.00788031,  0.04669908,
         -0.03068684, -0.02111541],
        [-0.02016227, -0.01541298, -0.04182852, -0.00293314,
         -0.00842098,  0.01841248, -0.00788031,  0.04669908,
         -0.03068684, -0.02111541],
        [ 0.03044732, -0.01198733, -0.0395214 , -0.00900893,
          0.03482536,  0.02317161,  0.02188138,  0.03744301,
         -0.02859542, -0.0459818 ],
        [ 0.01091182, -0.03709688,  0.03638076, -0.00696682,
          0.00861124, -0.02215153,  0.01821219, -0.0483763 ,
          0.01577869,  0.02980197],
        [ 0.01129099, -0.04511006,  0.01248759,  0.0